version: '3.8'

services:
  db:
    image: postgres:15.2
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - db.env
    networks:
      - caption-pal
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - caption-pal

networks:
  caption-pal:
    driver: bridge
